feat: Add Mailgroup, SetUser related functions
twreporter/go-api pull request #537
Opened 2023-04-01 21:54 UTC by howar31

# Issue
New function for setting user's preferences, including maillist related

# Notice
- only SetUser completed
- GetUser has table join issue
- unit test will be delievered in another commit

# Dependency

2023-04-11 04:12 UTC, Aylie-Chou commented on models/user_preferences.go
> +	Topics   []string `json:"topics"`
Could we use the same naming  `ReadPreference` here for the consistency

2023-04-11 07:16 UTC, Aylie-Chou commented on storage/mailgroup.go
> +	err := gs.db.Exec("DELETE FROM users_mailgroups WHERE user_id = ?", uid).Error
question: would the syntax `?` provide the same protection as sql parameter ?

2023-04-14 02:13 UTC, Aylie-Chou commented
Could we add some test case for new added endpoints ?

2023-04-17 03:10 UTC, howar31 commented on storage/mailgroup.go
> +	err := gs.db.Exec("DELETE FROM users_mailgroups WHERE user_id = ?", uid).Error
Yes, Exec will prepare the statement and handle the injection issue.

2023-05-03 04:42 UTC, Aylie-Chou commented on tests/controller_user_test.go
> +type UserPreferences struct {
Could we use the defined `UserPreferences` model in `models/user_preferences.go` here ?

2023-05-03 04:46 UTC, Aylie-Chou commented on tests/controller_user_test.go
> +		ReadPreference: []string{"test1", "test2"},
`read_preference` field has defined acceptable value list.
`test1`, `test2`  would not be allowed to save to db

2023-05-03 04:54 UTC, Aylie-Chou requested changes
Appreciate the hard work !
We would still need a list for `maillist` from api attributes to mailchimp id.
And also it would be better to add failed case in `user_test.go`

I left some cooments, please have a look.

2023-05-07 20:33 UTC, howar31 commented on tests/controller_user_test.go
> +type UserPreferences struct {
done

2023-05-07 20:33 UTC, howar31 commented on tests/controller_user_test.go
> +		ReadPreference: []string{"test1", "test2"},
done

2023-05-15 08:54 UTC, Aylie-Chou commented on controllers/user.go
> +	if !isValidMaillistValue(preferences.Maillist) {
Could we check maillist validation before update read preference since `SetUser` would return error despite update read preference success or not.

2023-05-15 09:03 UTC, Aylie-Chou commented on storage/user.go
> +	err = gs.db.Save(&user).Error
Question: why do we need to save all `user` object here (instead of saving `read_preference` field only)
If there's other function updating another field of user, this may cover other's results.

2023-05-15 09:06 UTC, Aylie-Chou requested changes
The test cases look good on this version 👍
Consider that `mailchimp` also have staging environment, we would need to make interest ids configs to support it.
Please have a look to the new added comments & feel free to discuss !

2023-05-22 03:30 UTC, howar31 commented on storage/user.go
> +	err = gs.db.Save(&user).Error
By saving the entire user object, we guarantee that the changes made to ReadPreference and any other fields are saved atomically. Atomicity ensures that either all changes are saved successfully or none at all. If we were to save individual fields separately, it would be harder to ensure the atomicity of updates across multiple fields.

2023-05-22 20:35 UTC, howar31 commented on controllers/user.go
> +	if !isValidMaillistValue(preferences.Maillist) {
done

2023-05-22 20:35 UTC, howar31 commented on models/user_preferences.go
> +var InterestIDs = []string{
done

2023-05-22 20:35 UTC, howar31 commented on storage/mailgroup.go
> +		return errors.Wrap(err, "insert user mailgroup error")
done

2023-05-22 20:35 UTC, howar31 commented on storage/user.go
> +	err = gs.db.Save(&user).Error
done

2023-05-23 01:51 UTC, Aylie-Chou commented on models/user_preferences.go
> +var InterestIDs = []string{
Consider that mailchimp also have staging environment, we would need to make interest ids configs to support it.

2023-05-23 01:59 UTC, Aylie-Chou commented on storage/user.go
> +	err = gs.db.Save(&user).Error
Good job to use `transaction` !
After applying transaction, do we still have to query & save whole user object ?
(we do not check the validation of queried object)

2023-05-23 02:06 UTC, Aylie-Chou requested changes
The `transaction` looks good.
There's two comment left to resolve:
- the `mailchimp` interest id would need configurated
- `transaction` pormise the atomic of `UpdateReadPreferenceOfUser`.  The previous `query & save` could be simplified as:
  - query & check queried data(id) & save target field only
    - I vote this one cause userId is the user-input parameter
  - save target field only

2023-05-23 08:17 UTC, howar31 commented on models/user_preferences.go
> +var InterestIDs = []string{
done

2023-05-23 16:26 UTC, Aylie-Chou commented on configs/config.go
> +        operational_journal: 092053aaa1 # 報導者營運手記
May we set the default value of interest id as staging version

2023-05-23 16:26 UTC, Aylie-Chou commented on models/user_preferences.go
> +var InterestIDs = map[string]string{
Would we still need this var after add interest id config ?

2023-05-24 08:09 UTC, howar31 commented on configs/config.go
> +        operational_journal: 092053aaa1 # 報導者營運手記
done

2023-05-24 08:17 UTC, Aylie-Chou approved these changes
LGTM

2023-05-24 08:20 UTC, merged