feat: implement GetUser API and activated status
twreporter/go-api pull request #552
Opened 2023-06-06 22:25 UTC by howar31

# Issue
- New API: GetUser
- New migration: activated field in users table
- Modify API: add activated in login response
- Modify API: set activated after set interests and donate step 2

# Notice

# Dependency

2023-06-09 06:41 UTC, Aylie-Chou requested changes
Mostly looking good.
I left some comments about previous discussion or mismatch deisign, please have a look.

2023-06-09 06:41 UTC, Aylie-Chou commented on doc/user.apib
> ++ activated: `2023-06-01T01:23:45Z` (string) - The activated status of the user. If the user is not activated, the value is null.
According to [design doc](https://www.notion.so/twreporter/User-API-6fb09be7357745dbbabf68d0fbc278ad?pvs=4), the type of `activated` column would be `boolean`.
Do we have any specific reason to change its type ?

2023-06-09 06:41 UTC, Aylie-Chou commented on storage/user.go
> +	err := gs.db.Preload("Roles").First(&user, "id = ?", userID).Error
According to api doc, the return data of `user.role` would be role name string.
Looks like we could preload `Roles.name` only here ?

2023-06-09 06:41 UTC, Aylie-Chou commented on storage/user.go
>  func (gs *GormStorage) GetUserByID(userID string) (models.User, error) {
As previous discussion, the return data `user.maillist` would need to be mapped to maillist keys.

2023-06-09 06:41 UTC, Aylie-Chou commented on doc/user.apib
> ++ name: Full Name (string) - The full name of the user
As previous discussion, please help to change `name` into firstname, lastname.

2023-06-09 06:41 UTC, Aylie-Chou commented on controllers/donation.go
> +	matchedUser, err := mc.Storage.GetUserByEmail(reqBody.Cardholder.Email)
Could we update activated value with concurrency in order not to block `CreateAPeriodicDonationOfAUser` ?

2023-06-14 01:29 UTC, howar31 commented on doc/user.apib
> ++ activated: `2023-06-01T01:23:45Z` (string) - The activated status of the user. If the user is not activated, the value is null.
As the discussion, it was decided to change the boolean data type to timestamp in order to store more information without significantly impacting performance.

2023-06-14 01:29 UTC, howar31 commented on storage/user.go
> +	err := gs.db.Preload("Roles").First(&user, "id = ?", userID).Error
We loaded `name` and `name_en` here.  I think it's ok to preload Roles.

2023-06-14 01:29 UTC, howar31 commented on storage/user.go
>  func (gs *GormStorage) GetUserByID(userID string) (models.User, error) {
according to Asana tasks, we return email, registered date and roles.  maillist is not implemented in this commit.

2023-06-14 01:29 UTC, howar31 commented on doc/user.apib
> ++ name: Full Name (string) - The full name of the user
done

2023-06-14 01:59 UTC, howar31 commented on controllers/donation.go
> +	matchedUser, err := mc.Storage.GetUserByEmail(reqBody.Cardholder.Email)
done

2023-06-14 06:02 UTC, Aylie-Chou commented on controllers/donation.go
> +	matchedUser, err := mc.Storage.GetUserByEmail(reqBody.Cardholder.Email)
if the return data of `GetUserByEmail` is only for updating user's activated status, could we also move it into the concurrent function ?

2023-06-14 06:09 UTC, Aylie-Chou commented on doc/user.apib
> ++ roles: explorer, action_taker, trailblazer (array) - The roles of the user
looks like the return value of `roles` is array of object. Could we specify what info would be contianed in the object here ?

2023-06-14 06:10 UTC, Aylie-Chou commented on storage/user.go
>  func (gs *GormStorage) GetUserByID(userID string) (models.User, error) {
updated in commit [3285298](https://github.com/twreporter/go-api/pull/552/commits/3285298385862ca61aa94dd4e982b6e571193df2).

2023-06-14 06:12 UTC, Aylie-Chou requested changes
Thanks for the quick resolving for the `getUser` return data.
Please have a look at the comments & feel free for any discussion.

2023-06-14 07:02 UTC, howar31 commented on controllers/donation.go
> +	matchedUser, err := mc.Storage.GetUserByEmail(reqBody.Cardholder.Email)
done

2023-06-14 07:03 UTC, howar31 commented on doc/user.apib
> ++ roles: explorer, action_taker, trailblazer (array) - The roles of the user
done

2023-06-14 07:10 UTC, Aylie-Chou approved these changes
LGTM 👍

2023-06-14 07:13 UTC, merged