feat: add role assign flow
twreporter/go-api pull request #556
Opened 2023-06-27 04:42 UTC by howar31

# Issue
- Add role assign function
- Add default role flow
- Add donation role flow

# Notice

# Dependency

2023-07-03 02:37 UTC, Aylie-Chou commented on configs/constants/constants.go
> +	RoleIdExplorer    = 1
Question: why do we choose `id` rather than `key` to be the constants ?

2023-07-03 02:52 UTC, howar31 commented on configs/constants/constants.go
> +	RoleIdExplorer    = 1
The `key` is a new column.  I'll merge the `key` related commit to this PR.

2023-07-04 08:36 UTC, Aylie-Chou requested changes
The code looks good with the role key !
Just have to check the details when assigning roles relationship. Please have a look at the comment.

2023-07-04 09:34 UTC, howar31 commented on configs/constants/constants.go
> +	RoleIdExplorer    = 1
done

2023-07-04 09:34 UTC, howar31 commented on storage/user.go
> +	association.Append(&role)
done with Replace()

2023-07-04 10:31 UTC, Aylie-Chou approved these changes
LGTM

2023-07-04 10:48 UTC, merged