feat: Add role assign related mails
twreporter/go-api pull request #566
Opened 2023-07-14 19:53 UTC by howar31

# Issue
Add role assign related mails:
- send_role_explorer
- send_role_actiontaker
- send_role_trailblazer
- send_role_downgrade (only route)

# Notice

# Dependency

2023-07-21 06:53 UTC, Aylie-Chou requested changes
Mostly looking good, and there's one thing to check:
would we need to add feature toggle here since `go-api` repo do not have `dev` branch/environment ?

2023-07-21 06:53 UTC, Aylie-Chou commented on controllers/account.go
> +		go mc.sendAssignRoleMail(constants.RoleExplorer, email)
Question: do we need to assign roles for the user before sending email ?

2023-07-21 06:53 UTC, Aylie-Chou commented on controllers/mail.go
> +func (contrl *MailController) SendRoleExplorerMail(c *gin.Context) (int, gin.H, error) {
It seems that the four added functions have some common codes. Could we combine them into a function to reduce duplicate codes ?

2023-07-21 06:53 UTC, Aylie-Chou commented on template/role-trailblazer.tmpl
> +<p dir="ltr"><span style="color:#404040"><span style="font-size:16px">★ 同時成為國家兩廳院的聯名會員</span></span></p>
It seems the content of html template is a bit different with the provided doc on [dirve](https://drive.google.com/drive/folders/1T1gDVHoiuB67XdgZBkzm63nyN7oQ49Bd).
Please help to check it.

2023-07-25 00:39 UTC, howar31 commented on template/role-trailblazer.tmpl
> +<p dir="ltr"><span style="color:#404040"><span style="font-size:16px">★ 同時成為國家兩廳院的聯名會員</span></span></p>
the template was updated on 20th July after this commit :/

2023-07-25 18:02 UTC, howar31 commented on controllers/account.go
> +		go mc.sendAssignRoleMail(constants.RoleExplorer, email)
The role has been assigned in `InsertUserByReporterAccount` before sending the mail.

2023-07-25 18:07 UTC, howar31 commented on controllers/mail.go
> +func (contrl *MailController) SendRoleExplorerMail(c *gin.Context) (int, gin.H, error) {
done

2023-07-27 02:53 UTC, Aylie-Chou requested changes
Previous comments all resolved !

As the discussion in refinement meeting, please help to check following feature:
- If user already on that role, we would not send upgrading mail again
- sending explorer email only when user is `activated`

Feel free for any questions/discussions !

2023-08-02 05:30 UTC, Aylie-Chou commented on controllers/account.go
> +		roleCheck, _ := mc.Storage.HasRole(matchedUser, constants.RoleExplorer)
Question: how would we handle the error of `HasRole` ?

2023-08-02 05:34 UTC, Aylie-Chou commented on controllers/donation.go
> +		roleCheck, _ := mc.Storage.HasRole(matchedUser, constants.RoleActionTaker)
Question: if the user has already been `trailblazer`, would the role changed to `action taker` here ?

2023-08-02 05:35 UTC, Aylie-Chou requested changes
Please have a look at comments & would we add `feature toggle` in this pr ?

2023-08-02 16:26 UTC, howar31 commented on controllers/donation.go
> +		roleCheck, _ := mc.Storage.HasRole(matchedUser, constants.RoleActionTaker)
Yes, it will.  The `HasRole` only check for specific role (`Action Taker` here, for example).

2023-08-04 01:41 UTC, Aylie-Chou commented on controllers/donation.go
> +		roleCheck, _ := mc.Storage.HasRole(matchedUser, constants.RoleActionTaker)
Is the role downgrading the expected spec ?

2023-08-04 01:46 UTC, Aylie-Chou commented on controllers/account.go
> +		roleCheck, _ := mc.Storage.HasRole(matchedUser, constants.RoleExplorer)
it sounds good.
could we also add the same handling in other `HasRole` check place (`controller/donation`) ?

2023-08-04 06:24 UTC, howar31 commented on controllers/account.go
> +		roleCheck, _ := mc.Storage.HasRole(matchedUser, constants.RoleExplorer)
All `HasRole` has similar error handlings.  They won't effect the original logics.

2023-08-04 06:34 UTC, howar31 commented on controllers/donation.go
> +		roleCheck, _ := mc.Storage.HasRole(matchedUser, constants.RoleActionTaker)
Fix patched

2023-08-04 06:55 UTC, howar31 commented
According to discussion in meeting, the feature toggle will be implemented in another PR

2023-08-04 08:35 UTC, howar31 commented on controllers/donation.go
> +		roleCheck, _ := mc.Storage.HasRole(matchedUser, constants.RoleActionTaker)
orz

2023-08-07 23:22 UTC, merged