feat: Add OTP login APIs
twreporter/go-api pull request #606
Opened 2023-09-04 04:33 UTC by howar31

# Issue
Add OTP login APIs
- /v1/mail/send_otp
- /v3/auth/signin
- /v3/auth/activate

# Notice

# Dependency

2023-09-05 06:47 UTC, Aylie-Chou commented on controllers/account.go
> +		if err != nil {
Question: should we determine error case or matchedUser nil case here ?

2023-09-14 20:07 UTC, howar31 commented on controllers/account.go
> +	return http.StatusOK, gin.H{
As discussion in meeting, the redirect will be implemented by frontend.  Backend will set cookie header only.

2023-09-22 07:21 UTC, Aylie-Chou commented on controllers/account.go
> +			"status": "fail",
Could we use `expired` as status value here to help frontend identify the fail cases 🙏

2023-09-26 19:32 UTC, howar31 commented on controllers/account.go
> +			"status": "fail",
done

2023-09-27 01:22 UTC, Aylie-Chou requested changes
There's one comment left, please have a look ~
Also could we have test cases for the new added function & update `/v3/activate` route `403` error info in api doc in next PR (not blocking this feature, but also important) 🙏

2023-10-02 03:33 UTC, howar31 commented on controllers/account.go
> +		if err != nil {
According to other similar functions (L110, L133), we do not need to determine error case or matchedUser nil case here.

2023-10-02 07:20 UTC, Aylie-Chou commented on controllers/account.go
> +		if err != nil {
If `matchedUser` and `err` are both nil, current code would still mark the user existed.
Is that the expected result ?

2023-10-02 17:07 UTC, Aylie-Chou reviewed
Please have a look at the new added comment.

2023-10-04 14:56 UTC, howar31 commented on controllers/account.go
> +		if err != nil {
I tried the `GetUserByEmail()`.  If `matchedUser` is nil (user not found), the `err` will return `record not found` error.  Normally they won't both be nil.

2023-10-04 15:42 UTC, Aylie-Chou commented on controllers/account.go
> +		if err != nil {
Got it !
Thanks for the checking.

2023-10-04 15:43 UTC, Aylie-Chou approved these changes
LGTM

2023-10-04 17:07 UTC, merged