feat: support multiple roles
twreporter/go-api pull request #624
Opened 2023-10-16 03:39 UTC by Aylie-Chou

# Issue
[[會員制]兩廳院會員合作](https://app.asana.com/0/1203699264568808/1205601884497079/f)

# Dependency
N/A

2023-10-19 04:02 UTC, howar31 requested changes

2023-10-19 04:02 UTC, howar31 commented on storage/user.go
> +		return db.Where(fileterExpired).Order("weight desc").Limit(1)
如果有多個 role 是一樣的 weight
(類似的合作例如 `action_taker_ntch` `action_taker_other1` `action_taker_other2` 有可能都會 assign 相同的 weight)
這樣回傳的 role 會每次都不一樣

目前想法是如果我們會設定成一樣的 weight ，可能那些 role 的意義和功能應該差不多
但若未來有其他依據 role key 判斷的功能，可能會產生 ambiguous？

2023-10-19 08:40 UTC, Aylie-Chou commented on storage/user.go
> +		return db.Where(fileterExpired).Order("weight desc").Limit(1)
目前的 code 是以 weight 不會 assign 一樣的值為前提設計的
未來的合作形式不知道會是什麼樣子，我想到時候可以再依據需求做相對應的修改

2023-10-19 08:43 UTC, Aylie-Chou commented on migrations/000014_add_user_source_and_multiple_roles.up.sql
> +-- update roles.weight value
Sure, updated in notion schema [doc](https://www.notion.so/twreporter/roles-b7cda5d35974496dbdb07cfea0b52387?pvs=4).

2023-10-20 01:31 UTC, howar31 commented on storage/user.go
> +		return db.Where(fileterExpired).Order("weight desc").Limit(1)
OK，我在 Notion schema 內註記這件事了！

2023-10-20 01:31 UTC, howar31 approved these changes
LGTM

2023-10-24 08:11 UTC, merged