feat: add / update endpoints for post followups
twreporter/go-api pull request #721
Opened 2024-06-13 18:57 UTC by Aylie-Chou

# Issue
[[會員制]重要報導追蹤-後端實作](https://app.asana.com/0/1203699264568808/1207085276870885/f)

# Dependency
N/A

2024-06-18 06:25 UTC, liruchen32 requested changes
Just a small question

2024-06-18 06:25 UTC, liruchen32 commented on internal/mongo/document.go
> +			//{Key: "state", Value: "published"},
Can we remove this line?

2024-06-18 08:02 UTC, Aylie-Chou commented on internal/mongo/document.go
> +			//{Key: "state", Value: "published"},
no, this line should be included 😂
updated in [e40f6bd](https://github.com/twreporter/go-api/pull/721/commits/e40f6bd3bc2094cc594186beb47536fb12f6aa06)

2024-06-19 07:04 UTC, liruchen32 approved these changes
LGTM

2024-06-19 09:45 UTC, merged