Feature/get post toggle bookmark
twreporter/go-api pull request #732
Opened 2024-07-05 06:59 UTC by liruchen32

# Issue
[[維運] redux 升級後續 refactor: 書籤](https://app.asana.com/0/1203699264568808/1207639742964814/f)

# Notice

# Dependency

2024-07-08 07:22 UTC, Aylie-Chou commented on controllers/news_v2.go
> +		if fullPost, ok := post.(news.Post); ok {
Question: why do we need to add type convertion (news.Post) here ?

2024-07-08 07:32 UTC, Aylie-Chou commented on internal/news/query.go
> +		q.ToggleBookmark = toggleBookmark
Could we also add `q.ToggleBookmark` in `ParsePostListQuery` ?

2024-07-08 07:33 UTC, Aylie-Chou commented on storage/news_v2.go
> +		return models.UsersBookmarks{}, errors.New("userID is required")
Question: why do we choose to return empty struct rather than `nil` when error ?

2024-07-08 07:36 UTC, Aylie-Chou commented on storage/news_v2.go
> +		targetBookmark = result.Content.(models.UsersBookmarks)
targetBookmark, ok ?

2024-07-08 07:36 UTC, Aylie-Chou commented on storage/news_v2.go
> +		log.Print(result)
remove debug log XD

2024-07-08 07:37 UTC, Aylie-Chou commented on storage/news_v2.go
> +	if userID == "" {
Question: do we also need to check post.ID exists ?

2024-07-08 07:40 UTC, Aylie-Chou commented on storage/news_v2.go
> +			log.WithField("detail", err).Errorf("%s", f.FormatStack(err))
error could be returned by `fetchResult{Error: errors.WithStack(err)}` & check `result.Error != nil` in receiver (looks like the receiver has already catch it)

2024-07-08 07:41 UTC, Aylie-Chou commented on storage/news_v2.go
> +		err := gs.db.Where("user_id = ? AND post_id = ?", userID, postID).Find(&UserBookmark).Error
(nice to have) Could we also match `post_id` rather than `slug` in `GetBookmarksOfPosts` XD

2024-07-08 07:42 UTC, Aylie-Chou requested changes
as comments~~

2024-07-08 08:40 UTC, liruchen32 commented on controllers/news_v2.go
> +		if fullPost, ok := post.(news.Post); ok {
cause `post` type is interface{}

2024-07-08 08:41 UTC, liruchen32 commented on internal/news/query.go
> +		q.ToggleBookmark = toggleBookmark
OK

2024-07-08 08:43 UTC, liruchen32 commented on storage/news_v2.go
> +	if userID == "" {
already check

2024-07-08 08:45 UTC, liruchen32 commented on storage/news_v2.go
> +		return models.UsersBookmarks{}, errors.New("userID is required")
cannot use nil as models.UsersBookmarks value in return statement

2024-07-08 08:47 UTC, liruchen32 commented on storage/news_v2.go
> +		log.Print(result)
fixed

2024-07-08 08:47 UTC, liruchen32 commented on storage/news_v2.go
> +		targetBookmark = result.Content.(models.UsersBookmarks)
fixed

2024-07-08 08:47 UTC, liruchen32 commented on storage/news_v2.go
> +			log.WithField("detail", err).Errorf("%s", f.FormatStack(err))
fixed

2024-07-09 07:43 UTC, Aylie-Chou commented on storage/news_v2.go
> +		return models.UsersBookmarks{}, errors.New("userID is required")
okay, I think we could refactor it to return the pointer version in the future.

2024-07-09 07:44 UTC, Aylie-Chou approved these changes
LGTM

2024-07-09 08:00 UTC, merged